apiVersion: apps/v1
kind: Deployment
metadata:
  name: clicknbuy
  labels:
    app: clicknbuy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clicknbuy
  template:
    metadata:
      labels:
        app: clicknbuy
    spec:
      containers:
        - name: clicknbuy
          image: ghcr.io/jenith-datatemplate/java-devsecops-pipeline:sha-720e61a271a12d8098644deace946438c658c0de
          imagePullPolicy: Always
          ports:
            - containerPort: 5454
          envFrom:
            - secretRef:
                name: clicknbuy-secrets
          resources:
            limits:
              cpu: "1"
              memory: "768Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5454
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5454
            initialDelaySeconds: 60
            periodSeconds: 5
      imagePullSecrets:
        - name: github-container-registry
